name: Open PR from feature branch to 17.0-dev

on:
  pull_request:
    branches:
      - 17.0
    types: [opened, reopened, synchronize]

jobs:
  call-shared-workflow:
    uses: tawasta/github-workflows/.github/workflows/open-pr-to-dev.yml@main
    with:
      target_branch: 17.0-dev
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}