name: pre-commit

on:
  pull_request:
    branches:
      - "17.0*"
  push:
    branches:
      - "17.0"

jobs:
  pre-commit:
    uses: tawasta/github-workflows/odoo-pre-commit.yml@main
    with:
      python-version: '3.11'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}